default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  host: localhost
  port: 5432
  pool: 50

development:
  <<: *default
  database: sample_app

test:
  <<: *default
  database: sample_app

production:
  <<: *default
  database: sample_app
